# This file contains values from Cookiecutter

default_context:
  project_name: "pre_hhat"
  project_description: "A micro H-hat version."
  organization: "exo-labs"
  license: "MIT"
  minimal_python_version: 3.8
  github_name: "Doomsk"
  email: "eduardo.maschio@theqube.io"
  version: "0.1.0"
  line_length: "100"
  create_example_template: "cli"
